# Generated by Django 5.1.6 on 2025-02-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[('gpt-4o-mini', 'Gpt 4O Mini'), ('gpt-4o', 'Gpt 4O')], default='gpt-4o-mini', max_length=255)),
                ('response', models.TextField(default='', editable=False)),
            ],
        ),
    ]
